### ISSUE TITLE
Collection caching

### ISSUE THREAD

**Issue by sigfrid** [igorkasyanchuk/cache_with_locale#1]
Is this gem supposed to work with collection caching?
https://guides.rubyonrails.org/caching_with_rails.html#collection-caching

```
<%= render partial: 'avatar',
               collection: User.heroes,
               as: :user,
               cached: true %>
```

Thanks

**Comment by igorkasyanchuk** [comment]
yeap, I think should work well

**Comment by sigfrid** [comment]
Thanks.
